services:
  mysqldb:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=abc
      - MYSQL_PASSWORD=abc123
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/0_init.sql
      - db:/var/lib/mysql

  bezkoder-api:
    depends_on:
      - mysqldb
    container_name: api
    build: ./bezkoder-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=sample.hcldevopscoe.com
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_LOCAL_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN

  bezkoder-ui:
    depends_on:
      - bezkoder-api
    restart: unless-stopped
    container_name: ui
    env_file: ./.env
    build:
      context: ./bezkoder-ui
      args:
        - ANGULAR_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $ANGULAR_LOCAL_PORT:$ANGULAR_DOCKER_PORT

volumes:
  db:
